Set `workshop shell` cwd to /project
canonical/workshop pull request #170
Opened 2024-09-20 08:20 UTC by jy5275

# Description

Currently,`workshop shell` opens a session with $HOME as a work directory. 

This PR changes it to `/project`, in order to be consistent with the default of `workshop exec`.

https://warthogs.atlassian.net/jira/software/c/projects/WSP/boards/1645?selectedIssue=WSP-36

# Self-review quick check

 * [√] Make decisions that cost a lot to reverse explicit in the PR description.
 * [√] Avoid nested conditions.
 * [√] Delete dead code and redundant comments.
 * [√] Normalise symmetries by sticking to doing identical things identically. 
 * [√] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [√] Put variable declaration and initialisation together.
 * [√] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [√] Put a blank line between two logically different chunks of code.

2024-09-21 05:17 UTC, dmitry-lyfar commented
@jy5275 spread tests are failing.

2024-09-22 03:14 UTC, jy5275 commented
> @jy5275 spread tests are failing.

Yes I deliberately added a fail command to see if spread test works. Will revert it

2024-09-23 00:50 UTC, dmitry-lyfar commented
Thanks, you'd need to rebase against main as the github workflows had to change due to some actions being moved across repos and breaking our flows, that was fixed in main.

2024-09-26 23:40 UTC, dmitry-lyfar commented on cmd/workshop/exec.go
> -	return cmd.execCommand.Run(c, []string{av[0], "su", "-l", "workshop"})
@jy5275 what is the reason for dropping "-l"? Also, that does not seem to change cwd to /project?

2024-10-05 14:27 UTC, jy5275 commented
Have updated to make `workshop shell` to get a login shell

2024-10-06 20:23 UTC, dmitry-lyfar requested changes
@jy5275 it is getting closer, thank you, see my comments.

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/workshop.go
> +	UserData string
This is an internal detail, it should never be exposed publicly. Your integration tests need to use GetInstance LXD API to obtain the value of a user.* configuration attribute.

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/workshop.go
> +	UserData string
```suggestion
```

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/workshop.go
> +	UserData string
Note how other properties here are agnostic of LXD API data types. These must not leak out to the client code. `user.user-data` key is a LXD specific configuration key, imagine if we want to replace LXD with some other backend.

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/workshop.go
> +	ConfigUserData          = "user.user-data"
```suggestion
```

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +	c.Assert(userData[0:14], check.Equals, "#cloud-config\n")
@jy5275 strings.HasPrefix

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +	userData := ws.UserData
You can use GetInstance LXD API to fetch the cloud init config.

2024-10-06 20:23 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +		UserData: inst.Config[workshop.ConfigUserData],
```suggestion
```

2024-10-07 03:05 UTC, jy5275 commented on internal/workshop/workshop.go
> +	UserData string
I added a method `lxdbackend.Backend.GetWorkshopConfig()` to replace `Workshop.UserData` field.

However, this requires Adding a type assertion in `workshop_test.go` (assert `Backend` interface type to `lxdbackend.Backend`). Could you help to check if this is acceptable?

2024-10-08 01:11 UTC, dmitry-lyfar requested changes
Thank you, one more pass is needed, please also resolve the unresolved comments/suggestions.

2024-10-08 01:11 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +	if !ok {
Thanks, what we should do here is to refactor the test suite so it works with a concrete implementation. Please update f.bd to be of `*lxdbackend.Backend` type and that will rid you of this unnecessary type assertion. This is an integration test for the LXD backend anyway.

2024-10-08 01:11 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +func (f *wsOps) TestLxdBackendWorkshopUserData(c *check.C) {
The test should have a different name, it is not about user-data but about validating the cloud-init config (specifically, the part about changing a user's default directory).

2024-10-08 01:12 UTC, dmitry-lyfar commented on internal/workshop/workshop.go
> +	UserData string
Answered in a separate thread.

2024-10-08 01:15 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +write_files:
Since there is an integration test, you can validate that it actually works by checking the content of .profile.

2024-10-08 10:51 UTC, jy5275 commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +func (f *wsOps) TestLxdBackendWorkshopUserData(c *check.C) {
Thanks for pointing out. 

However, this function validates the whole config string, rather than just the module to change the default dir. So I think `TestLxdBackendWorkshopCloudInitConfig` may be better (without `ChangeDefaultDir...`)

2024-10-15 09:38 UTC, dmitry-lyfar reviewed
Looks pretty good, see my comments.

2024-10-15 09:38 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_test.go
> +	c.Assert(len(userData) > 0, check.Equals, true)
```suggestion

```

2024-10-15 09:38 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_exec_test.go
> +func (f *wsExec) TestLxdBackendExecCheckProfile(c *check.C) {
@jy5275 I know that we discussed that above, but I think this test knows too much about the implementation detail. We need to shell into the workshop and confirm that CWD is /project. We don't have to check the content of the .profile as this may change, for example, for other shells.

2024-10-16 03:49 UTC, jy5275 commented on internal/workshop/lxd/tests/integration/workshop_exec_test.go
> +func (f *wsExec) TestLxdBackendExecCheckProfile(c *check.C) {
> We need to shell into the workshop and confirm that CWD is /project

Yes. But as discussed in a previous call, it's hard to check CWD of `shell` subcommand in `tests/main/shell/task.yaml`, as spread uses non-interactive shell. How should we achieve that?

2024-10-16 20:35 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_exec_test.go
> +func (f *wsExec) TestLxdBackendExecCheckProfile(c *check.C) {
@jy5275 why do we need interactivity in this integration test? You can execute a command in a login shell that is not interactive in this test, `sudo -i -u workshop -- pwd`

2024-10-20 16:32 UTC, dmitry-lyfar requested changes

2024-10-20 16:32 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_exec_test.go
> +	// Verify that login dir is /home/workshop, not /project
@jy5275 the comment is incorrect.

2024-10-20 16:32 UTC, dmitry-lyfar commented on tests/main/exec/task.yaml
> +  workshop_exec exec ws-exec --uid=0 -- su -l workshop -w "WORKSHOP_SHELL" -c pwd | MATCH '/home/workshop'
@jy5275 it is ok to do this in the integration test, but what is the point of doing it in the end to end test? The end to end test must verify the user-facing behavior, which is `workshop shell`. Now this test (almost) duplicates the integration test.

2024-10-20 16:32 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/helper/helper.go
> +	os.MkdirAll("/tmp/workshop/project", 0755)
@jy5275 who is going to clean this directory after the tests have ran? See c.Mkdir() for such purposes.

You can create a wrapper func for DefaultTestDevices which has a project as an argument and returns a `func ()map[string]map[string]string` to accommodate this change in this test suite.

2024-10-21 05:44 UTC, jy5275 commented on internal/workshop/lxd/tests/helper/helper.go
> +	os.MkdirAll("/tmp/workshop/project", 0755)
I've updated code to ensure the temporary project dir gets removed after each time intergraion runs.

In order not to change the signature of `DefaultTestDevices`, I created new functions `getDefaultDevicesWithProject` and `FakeDefaultDevicesWithProject` - that makes the invokation chain a little more complicated. Could you help to see if it's acceptable?

2024-10-21 11:46 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/helper/helper.go
> +	os.MkdirAll("/tmp/workshop/project", 0755)
@jy5275 I don't see it in the latest commit, there is only the e2e test removal.

What I mean is:

```
func execTestDevices(projectDir string) func () map[string]map[string]string {
    conf := DefaultTestDevices()
    conf["workshop.project"] = projectDir
    return func () map[string]map[string]string {
                return conf
    }
}
```

which then can be called:

```
	f.restoreDevices = lxdbackend.FakeDefaultDevices(execTestDevices(c.Mkdir()))
```

so, you don't have to delete it manually, it is done by the test framework already.

2024-10-22 11:32 UTC, dmitry-lyfar commented on internal/workshop/lxd/tests/integration/workshop_exec_test.go
> +	f.restoreDevices = lxdbackend.FakeDefaultDevicesWithProject(helper.DefaultTestDevices, tmpProjectPath)
@jy5275 we don't need Fake function for every variation of the DefaultTestDevices, that's why the adapter I suggested should be used, so you don't have to create another Fake* function

2024-10-22 11:34 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +		os.MkdirAll(projectPath, 0755)
@jy5275 please check my example with more attention to how it should be done. It must use c.Mkdir. See how it is done elsewhere in the codebase, do not do it inconsistently. It is a common problem that has been solved, no need to invent another solution.

2024-10-22 16:32 UTC, jy5275 commented on internal/workshop/lxd/lxd_backend.go
> +		os.MkdirAll(projectPath, 0755)
Thanks for your suggestion. I just noticed that the refered function should be `c.MkDir` - I misunderstood it as `os.Mkdir` before.
Things get a lot easier with the test framework automatically removing the dir for us.

2024-12-09 22:20 UTC, lachypjones commented
Hey @jy5275 
The '-D' option (and the associated Chdir_Spec) are only compatible with sudo versions 1.9.3 or higher (see https://www.sudo.ws/docs/man/sudoers.man/#Chdir_Spec). 
Ubuntu 20.04 uses sudo versions 1.8.x (see https://launchpad.net/ubuntu/focal/+source/sudo). 

This change would unfortunately mean that shell wouldn't work on a workshop using 20.04.

Can you see if there are any workarounds?

2024-12-10 04:41 UTC, jy5275 commented
> Hey @jy5275 The '-D' option (and the associated Chdir_Spec) are only compatible with sudo versions 1.9.3 or higher (see https://www.sudo.ws/docs/man/sudoers.man/#Chdir_Spec). Ubuntu 20.04 uses sudo versions 1.8.x (see https://launchpad.net/ubuntu/focal/+source/sudo).
> 
> This change would unfortunately mean that shell wouldn't work on a workshop using 20.04.
> 
> Can you see if there are any workarounds?

Thanks for pointing that out @lachypjones .

I just found sudo versions < 1.9.3 doesn't have an similar option to change working dir, and Ubuntu version < 22.04 can't upgrade sudo package to 1.9.3 

@dmitry-lyfar I suggest to adopt the previous way (update `/etc/profile.d/xxx.sh` to `cd /project` when starting a login shell) to achieve the goal. 

Specifically, revert [this commit](https://github.com/canonical/workshop/pull/170/commits/b905954c2fc0a9429ee9a55b994dd2d6954874d9). Is that OK?

2024-12-11 00:35 UTC, dmitry-lyfar commented
@jy5275 we will have to revert to support 20.04, but I would suggest a slightly different solution to not make the workshop containers depended on the default shell and keep it in the client for now (so no changes to the cloud-init):

```
sudo -i -u workshop bash -c "cd /project; exec bash -l"
```

2024-12-11 08:26 UTC, jy5275 commented
> @jy5275 we will have to revert to support 20.04, but I would suggest a slightly different solution to not make the workshop containers depended on the default shell and keep it in the client for now (so no changes to the cloud-init):
> 
> ```
> sudo -i -u workshop bash -c "cd /project; exec bash -l"
> ```

I found that `sudo -u workshop bash -l` already satisfies our requirements, because `bash -l` doesn't change working dir. I've updated test cases accordingly.

2024-12-11 23:41 UTC, dmitry-lyfar approved these changes

2024-12-11 23:42 UTC, merged