Add shellcheck and rectify existing linting issues
canonical/workshop pull request #183
Opened 2024-10-03 08:26 UTC by lachypjones

# Description
Shellcheck is a well known shell script static analysis tool. 
- Add shellcheck actions covering standard shell scripts and scripts contained in spread files
- Add snapd-testing-tools as a submodule to facilitate spread shell testing
- Rectify existing shellcheck warnings

# Self-review quick check
 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.

2024-10-03 08:29 UTC, lachypjones commented
Need to determine relative locations within the github runner to fix shellcheck lint.

2024-10-06 20:49 UTC, dmitry-lyfar requested changes
@lachypjones thanks! As an exception, we should rebase this PR to ensure clearer commit history. Generally, before pushing a PR for a review, make sure that all tests are passing locally, that'll help to reduce round trips and extra commits.

2024-10-06 20:49 UTC, dmitry-lyfar commented on tests/lib/utils.sh
> +      # quoting the following results in incorrect behavior
@lachypjones we need a specific reason, not just "incorrect behaviour". Otherwise, the explanation does not make sense for the reader.

2024-10-07 23:49 UTC, dmitry-lyfar approved these changes
Thank you! Once updated the description, please merge. Good stuff.

2024-10-08 01:44 UTC, merged