Doc: Add 'how to' for running a local store
canonical/workshop pull request #190
Opened 2024-10-09 07:05 UTC by lachypjones

# Description

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.

2024-10-09 09:03 UTC, akcano requested changes
Great job, thanks! Left a few comments, will do a full review when they're implemented.

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +
double empty line before heading titles

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +(ie. fake-store/sdk-store/my-sdk/latest/edge/my-sdk) and the
use `:file:` for paths; end directories with a slash for visibility:
```rst
:file:`/path/foo/bar/dir/` 
```

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +corresponding sdk definition (ie. my-sdk.yaml) should be renamed
```suggestion
corresponding SDK definition (i.e. :file:`my-sdk.yaml`) should be renamed
```

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +
double blank line

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +Workshop will now use the default URL
period at the end.

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +To go back to the default store, simply execute:
down with buzzwords

```suggestion
To go back to the default store:
```

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +That's it! Workshop will now pull from your local store
period, double blank line

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +    $ go run github.com/fsouza/fake-gcs-server@latest -data <path-to-dir-containing-sdk-store> -filesystem-root <same-as-data> -scheme http -port 8080 -public-host localhost:8080
line-wrap command sample

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +    my-sdk.sdk  sdk.yaml
separate output like this (indent to the starting character of the command):

```suggestion
.. code-block:: console
    $ ls fake-store/sdk-store/my-sdk/latest/edge

      my-sdk.sdk  sdk.yaml
```

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +The SDK should be placed in the most nested directory created above
be a bit more specific and imperative:

```suggestion
Place the SDK under the channel directory created at the previous step.
```

or 

```suggestion
Place the SDK in the deepest directory created at the previous step.
```

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +- <sdk> is the sdk name (ie. my-sdk)
use `:samp:` for placeholders and literal snippets, `:file:` for file/directory names
```suggestion
- :samp:`<sdk>` is the SDK name (ie. :samp:`my-sdk`)
```
etc.

2024-10-09 09:03 UTC, akcano commented on docs/how-to/run-local-store.rst
> +sdk names and channels. Because of this, when running
globally:

```suggestion
SDK names and channels. Because of this, when running
```

2024-10-11 00:19 UTC, dmitry-lyfar commented
@lachypjones @akcano thanks, looks good! One thing.

This should be part of the contributing document for developers as this is a mock (similar to how snapd organises its e2e testing that involves a store); this is something I'd like to have in the development documentation only (for testing purposes). Once the actual store is up, Workshop will work only with the Store provided by Canonical that is not possible to run self-hosted.

@lachypjones could you please move it there?

2024-10-11 05:58 UTC, akcano requested changes

2024-10-11 05:58 UTC, akcano commented on docs/contributing.rst
> +
Not sure where the duplication came from. Drop it, please, and we're done here. :)

```suggestion
```

2024-10-11 06:04 UTC, akcano commented
@dmitry-lyfar I'm entirely fine with having this as part of `CONTRIBUTING` for now, but this raises the question of whether `CONTRIBUTING` is for people who want to contribute to Workshop or for people who work on SDKs, because the subject matter itself crosses the line between Workshop and SDKcraft. 

The only reason I didn't suggest moving it to `CONTRIBUTING` in SDKcraft docs is that this relies on Workshop implementation details that would be out of place there.

2024-10-11 06:52 UTC, dmitry-lyfar commented
@akcano this was mostly done for developers who work on Workshop as they need to put up a local store for faster/easier testing locally (versus running a spread test that does it in prepare). So this is why we put it here, in the Workshop contributing guide. SDKcraft developers do not interact with a local store now.

2024-10-11 07:11 UTC, akcano approved these changes

2024-10-11 09:05 UTC, dmitry-lyfar approved these changes

2024-10-11 09:06 UTC, merged