Add Desktop interface
canonical/workshop pull request #203
Opened 2024-10-18 04:41 UTC by lachypjones

# Description
The desktop interface provides a method for a workshop to access the Wayland and/or X11 sockets of the host, enabling GUI-based applications and development.

Additionally, the desktop interface can be paired with the GPU interface to enable hardware-accelerated graphical applications

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.

## Docs

* [x] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [x] I have included the technical author in the review.

Or:

* [ ] I confirm the PR has no implications for documentation.

2024-10-30 09:14 UTC, akcano requested changes
LGTM with minor fixes.

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +execute Wayland GUI applications.
```suggestion
from inside the workshop,
allowing it to securely run Wayland GUI applications.
```

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +execute Wayland GUI applications.
https://sembr.org

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +building graphical applications or using editors without remote support.
```suggestion
which can be useful for various SDK-specific tasks
such as building graphical applications or using editors without remote support.
```

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +building graphical applications or using editors without remote support.
same

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +To check if the interface is connected:
```suggestion
- :envvar:`$WAYLAND_DISPLAY`
  Sets the Wayland socket name
  
- :envvar:`$XDG_SESSION_TYPE`
  Sets the current display server type

- :envvar:`$QT_QPA_PLATFORM`
  Sets the Qt platform plugin to be used for Qt applications

- :envvar:`$ELECTRON_OZONE_PLATFORM_HINT`
  Sets the preferred platform for Electron applications


To check if the interface is connected:
```

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +To check if the interface is connected:
envvar visibility, formatting convention, wording preferences

2024-10-30 09:14 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +This means the host's Wayland socket is available inside the workshop
```suggestion
     desktop    ws/desktop-sdk:desktop :desktop   manual


This means the host's Wayland socket is available inside the workshop:
```

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/builtin/desktop.go
> + * Copyright (C) 2016 Canonical Ltd
is the year ok?

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/builtin/desktop.go
> +		return fmt.Errorf("WAYLAND_DISPLAY is either empty or unset for user %q. Is this a wayland session?", user.Username)
```suggestion
		return fmt.Errorf("WAYLAND_DISPLAY is either empty or unset for user %q. Is this a Wayland session?", user.Username)
```

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
```suggestion
		return fmt.Errorf("failed to set up the desktop environment in profile.d for %q: %w", workshop, err)
```

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
verb form is mandatory, desktop change is optional

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/lxd_device/backend.go
> +			return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
same as above

2024-10-30 09:14 UTC, akcano commented on internal/interfaces/lxd_device/spec.go
> +// These are network protocol proxy devices and open a port on the host or in a workhop.
```suggestion
// These are network protocol proxy devices that open a port on the host or in a workhop.
```

2024-10-30 09:14 UTC, akcano commented on internal/workshop/lxd/lxd_backend_profile.go
> +			switch devtype {
maybe it's time for a map here

2024-10-30 09:17 UTC, lachypjones commented on docs/explanation/interfaces/desktop-interface.rst
> +execute Wayland GUI applications.
Good link, thankyou. I'd been trying to determine what the threshold for line breaks were.

2024-10-30 09:24 UTC, lachypjones commented on internal/workshop/lxd/lxd_backend_profile.go
> +			switch devtype {
Originally that's what I had refactored it to be, see:
https://github.com/canonical/workshop/pull/196

Dmitry suggested that it was best to refrain from making them generic (required to use a map where you suggested) as we don't yet know what else 'proxy' type devices may be used for.

2024-10-30 09:30 UTC, lachypjones commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
I agree the language was confusing.
The issue is that 'desktop' is the name of the interface and 'desktop environment' has it's own specific meaning. Suggest instead making the error:
`failed to configure the environment for interface: desktop in workshop: <workshop name> (<error>)`
Thoughts?
We then change the error string in other interfaces that configure the environment to match this format?

2024-10-30 11:04 UTC, akcano commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
fair enough, let's go with your suggestion for now

2024-10-30 11:05 UTC, akcano commented on internal/workshop/lxd/lxd_backend_profile.go
> +			switch devtype {
ok, the refactoring threshold is up to you guys

2024-11-05 20:57 UTC, dmitry-lyfar requested changes
It looks good, see the comments. Also, commit history: use -> Use.

2024-11-05 20:57 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +	// systemd is responsible for generating the "WAYLAND_DISPLAY" environment variable
The format of the code comments that I'm trying to get at: starts with a capital letter, plain English, sentences are separated with dots. Comments should be hard-wrapped with a width length 80 (for vscode, see the plugin named "Rewrap").

2024-11-05 20:57 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +// Why do we return autoconnect=true when allow-auto-connection is false?
These questions should not be here. It can go to the daily agenda for discussion.

2024-11-05 20:57 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +	// The container XDG_RUNTIME_DIR is always /run/user/1000 for the workshop user
Same note about comments applies here.

2024-11-05 20:57 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to configure the environment for interface: desktop in workshop: %q (%w)", workshop, err)
The error messaging in a similar ssh-agent interface for the env. setup failure starts with "cannot". So it should either be "failed" there or "cannot" here for the similar errors.

Also, that error message does not include the interface name, just the workshop name and an error string.

Let's bring it all to consistency.

2024-11-05 20:57 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +			return fmt.Errorf("failed to configure the environment for interface: desktop in workshop: %q (%w)", workshop, err)
Same note about error messaging applies here.

2024-11-05 20:57 UTC, dmitry-lyfar commented on tests/main/interface-desktop/task.yaml
> +summary: Check desktop-agent interface scenarios
desktop-agent?

2024-11-05 20:57 UTC, dmitry-lyfar commented on tests/main/interface-desktop/task.yaml
> +    echo '$WAYLAND_DISPLAY, $QT_QPA_PLATFORM, $XDG_SESSION_TYPE, $ELECTRON_OZONE_PLATFORM_HINT' | \
`test -v` should be used for checking if a variable is set / unset.

2024-11-06 00:59 UTC, lachypjones commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
@dmitry-lyfar 
Thoughts?
I can change ssh-agent to match or revert to what I had originally (which matched ssh-agent)

2024-11-06 01:43 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +		return fmt.Errorf("failed to setup the environment for desktop in profile.d for %q: %w", workshop, err)
@lachypjones I don't think we refer things like "interface: desktop" elsewhere. If you refer a workshop, that would be _"name" workshop_, see other error or log messages. Hence, _"desktop" interface_. For example,

```
return statusBadRequest("remount requires a content interface plug (provided plug is of %q interface)", conn.Plug.Interface())
```

So, I would prefer the desktop interface to comply with the rest.

2024-11-11 00:33 UTC, dmitry-lyfar commented
As per the internal discussion: support XWAYLAND too. The test apps:

```
sudo apt-get update
sudo apt install -y kitty
sudo apt install -y mesa-utils
sudo apt install -y x11-apps
```

2024-11-14 09:56 UTC, akcano requested changes
A few more improvements.

2024-11-14 09:56 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +The :command:`workshop connect` and :command:`workshop disconnect` commands
```suggestion
The :command:`workshop connect` and :command:`workshop disconnect` commands
```

2024-11-14 09:56 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +The :command:`workshop connect` and :command:`workshop disconnect` commands
Non-breaking spaces.

2024-11-14 09:56 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +  Sets the preferred platform for Electron applications
```suggestion
- :envvar:`$WAYLAND_DISPLAY`:
  Wayland socket name
  
- :envvar:`$XDG_SESSION_TYPE`:
  Current display server type

- :envvar:`$QT_QPA_PLATFORM`:
  Qt platform plugin to be used for Qt applications

- :envvar:`$ELECTRON_OZONE_PLATFORM_HINT`:
  Preferred platform for Electron applications
```

2024-11-15 05:39 UTC, dmitry-lyfar requested changes

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/systemd/user.go
> +func UserEnvironment(user *user.User) (map[string]string, error) {
This should accept a user name, see how it is done in a similar function called `func NormalizeUidGid(uid, gid *int, username, group string) (*int, *int, error)`

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/systemd/user.go
> +	env, err := osutil.ParseEnvironment(rawEnv)
`return osutil.ParseEnvironment(rawEnv)`

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +func (iface *desktopInterface) MountConnectedPlug(
This reads well. But we don't use this formatting and go full length in other places, so I suggest to leave it formatted as elsewhere (no new lines).

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +	// We pass through the X11 socket regardless of whether XAUTHORITY is present
This comment is not formatted correctly:

```
	// We pass through the X11 socket regardless of whether XAUTHORITY is
	// present on the host. This then gives users the option to modify their
	// xhost settings to allow connections from the container and container
	// user.
```

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +	if wayland == "" && display == "" {
This can move up to the point right after `env` is read for those variables.

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +			logger.Noticef("cannot copy Xauthority file for user %s, X11 applications may not work, %v", user, err)
`user` is a pointer that is attempted to be printed as `%s`

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +package wsutil
wsutil is `web socket util`. I don't think it aligns with x11.go well. It should be a separate package, it's ok to be a small package.

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +		err := wsutil.CopyXauthority(usr)
I think it makes sense to explain why it is being copied on every install call here.

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +		err := wsutil.CopyXauthority(usr)
```suggestion
		if err := wsutil.CopyXauthority(usr); err != nil {
```

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +		os.MkdirAll(destDir, 0744)
error handling? Also, 755?

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +	xauth, _ := env["XAUTHORITY"]
```suggestion
	xauth := env["XAUTHORITY"]
```

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +	// See migrateXauthority function inside of snapd for more info
I would copy/adapt the comment for the function here to not force the reader to go and look into the snapd's code base.

2024-11-15 05:39 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +	os.RemoveAll(destFile)
error handling?

2024-11-15 05:43 UTC, lachypjones commented on internal/wsutil/x11.go
> +package wsutil
Ah that makes sense. Apologies I just instinctively read it as 'workshoputil'

2024-11-17 21:04 UTC, dmitry-lyfar commented on tests/main/interface-desktop/task.yaml
> +  sudo -u ubuntu /bin/bash -c 'workshop connect ws-desktop/test-sdk-desktop:desktop :desktop'
interesting, why workshop_exec above and sudo -u here?

2024-11-17 21:08 UTC, dmitry-lyfar commented on internal/wsutil/x11.go
> +func CopyXauthority(user string) error {
Tests for CopyXAuthority?

2024-11-17 21:11 UTC, lachypjones commented on tests/main/interface-desktop/task.yaml
> +  sudo -u ubuntu /bin/bash -c 'workshop connect ws-desktop/test-sdk-desktop:desktop :desktop'
These are on the host, not in the workshop.

2024-11-17 21:15 UTC, dmitry-lyfar commented
I mean workshop connect call.

Also, bash -c doesn’t seem to be needed there?

On Mon, 18 Nov 2024 at 10:12, Lachlan Jones ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In tests/main/interface-desktop/task.yaml
> <https://github.com/canonical/workshop/pull/203#discussion_r1845652215>:
>
> > +  echo "Disconnect the desktop interface"
> +  workshop_exec disconnect ws-desktop/test-sdk-desktop:desktop
> +
> +  echo "Check that the environment is removed from the workshop"
> +  workshop_exec exec ws-desktop -- sudo -Hiu workshop /bin/bash -s <<"EOF"
> +      set -e
> +      [ -z "$WAYLAND_DISPLAY" ]
> +      [ -z "$QT_QPA_PLATFORM" ]
> +      [ "$XDG_SESSION_TYPE" == "unspecified" ]
> +      [ -z "$ELECTRON_OZONE_PLATFORM_HINT" ]
> +  EOF
> +
> +  echo "Connect the desktop interface for an x11 session"
> +  sudo -u ubuntu /bin/bash -c 'touch /tmp/.Xauthority'
> +  sudo -u ubuntu /bin/bash -c 'XDG_RUNTIME_DIR=/run/user/1000 systemctl --user set-environment DISPLAY=:0 XAUTHORITY=/tmp/.Xauthority'
> +  sudo -u ubuntu /bin/bash -c 'workshop connect ws-desktop/test-sdk-desktop:desktop :desktop'
>
> These are on the host, not in the workshop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/canonical/workshop/pull/203#discussion_r1845652215>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQVGPBFMYXLSKSPRHE7W63D2BEBCDAVCNFSM6AAAAABQFDSG32VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBRGIZDMNRYGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-17 21:57 UTC, lachypjones commented on internal/systemd/user.go
> +func UserEnvironment(user *user.User) (map[string]string, error) {
The reason I made the function accept the user.User struct was because on 3/4 of occasions where the UserEnvironment function is used, we also require the struct elsewhere in the same scope.

What do you think? (happy with either, I just wanted to explain my rationale)

2024-11-19 06:29 UTC, dmitry-lyfar requested changes
it gets better, I only commented on the latest commit's changes.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11.go
>  	if !osutil.IsDir(destDir) {
No need for this check, just run MkdirAll.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/spec.go
>  	pid  string
I think it does not need `pid`, looks like a rudimentary property.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  	defer restoreWorkshopdRunDir(dirs.WorkshopdRunDir)
See how other values are mocked. The form is this:

```
func FakeWorkshopRunDir(dir string) func() {
  old := dirs.WorkshopRunDir
  dirs.WorkshopRunDir = dir
  return func() {
    dirs.WorkshopRunDir = old
  }
}
```

and then

```
restore := FakeWorkshopRunDir("something")
defer restore()
```
or

```
// less readable
defer FakeWorkshopRunDir(path)()
```

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  	c.Assert(err.Error(), testutil.Contains, "Xauthority file isn't owned")
I would use ErrorMatches where possible with a full error message. It makes checking for consistency easier. Sometimes it is not practical and a regex can be used.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  func (x *X11TestSuit) TestCopyXAuthorityOwnershipFail(c *C) {
I cannot comment on the above line for some reason, but `TestCopyXAuthority` is not informative. Also, please do not import all names from the `check` package. I know it has been used in some packages, but this is not accurate and all new packages import only names they use.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  func (x *X11TestSuit) TestCopyXAuthorityOwnershipFail(c *C) {
Note, there is no need for empty Setup / Teardown.

2024-11-19 06:29 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  var userCurrent = user.Current
userCurrent is used once to get the current user, it is not mocked, so maybe we don't need it here?

2024-11-19 23:32 UTC, lachypjones commented on internal/x11/x11_test.go
>  	defer restoreWorkshopdRunDir(dirs.WorkshopdRunDir)
I understand that returning a closure that captures the old directory is clever, however I don't see the appeal for this type of function over using the defer argument evaluation semantics to give us the same thing in less lines (and arguably less cognitive overhead). 

As always, if you have a strong opinion on this (I understand that consistency is one, this feels slightly different to some of the other mocks I have seen however) I'm happy to take the closure approach.

2024-11-20 00:08 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  	defer restoreWorkshopdRunDir(dirs.WorkshopdRunDir)
@lachypjones this is about consistency, it should be done in a way as everywhere else unless there is a really good reason not to. 

Also, this allows for breaking locality for coupled entities, so, assignment and restoration happen in separate places. When reading restore, you will have to look for a value it is set to somewhere else and not in this line or, vice versa, when seeing the restoration logic, you'd need to look for where it is set.

2024-11-20 00:10 UTC, dmitry-lyfar commented on internal/x11/x11_test.go
>  	defer restoreWorkshopdRunDir(dirs.WorkshopdRunDir)
Another reason is you always must think about the order. If called in a reverse order, there will be no proper restore.

2024-11-20 00:11 UTC, lachypjones commented on internal/x11/x11_test.go
>  	defer restoreWorkshopdRunDir(dirs.WorkshopdRunDir)
Easy done. Thanks for the clear explanation.

2024-11-25 17:19 UTC, akcano requested changes

2024-11-25 17:19 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +This means the host's Wayland/X11 socket is available inside the workshop:
```suggestion
This means the host's Wayland or X11 socket is available inside the workshop:
```

2024-11-25 20:48 UTC, lachypjones commented on docs/explanation/interfaces/desktop-interface.rst
> +This means the host's Wayland/X11 socket is available inside the workshop:
@akcano, it's not an 'or' relationship, it's an 'and/or' relationship.
I felt that 'Wayland/X11' was cleaner than 'Wayland and/or X11'.

2024-11-26 04:11 UTC, dmitry-lyfar requested changes
Smoke test caused this error (two plugs, gpu and desktop in a hack SDK):

```
error: cannot perform the following tasks:
- Disconnnect desk/hack:gpu from desk/system:gpu (/var/lib/workshop/run/.Xauthority is not a directory)
"desk" refresh aborted
```

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +		x := &desktop.X11
Not sure why do we need another indirection here when you can just:

```
d := desktop{}
// ...
// Add wayland to the profile string
d.Wayland.Name = plug.Sdk().Name + "-" + "wayland"
d.Wayland.Connect = filepath.Join(xdg, wayland)
d.Wayland.Listen = filepath.Join("/run/user/1000/", wayland)
```

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop.go
> +		// Add X11 to the profile string
What is a profile string?

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/backend.go
> +		if _, err := os.Stat(dev.What); err != nil {
`osutil.FileExists`

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/spec.go
> +func (s *Specification) SetDesktop(desktop *workshop.Desktop) error {
Other similar methods receive a copy here. The pointer value internally is used to check if a device exists in a workshop.

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/spec.go
> +func addProxyEntry(s *Specification, entry *workshop.ProxyEntry, configKey string) {
Why is it a standalone method receiving `s`? It should be an unexported method of the Specification.

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/spec.go
> +	addProxyEntry(s, (*workshop.ProxyEntry)(&agent), "ssh-agent")
It's OK to create an `SshAgent` struct that would contain a `workshop.ProxyEntry` member instead of using aliases. It is extendable and avoids something like this.

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +		"raw.lxc":                  "lxc.mount.entry = tmpfs tmp tmpfs defaults",
We need to comment this well (with a link to the discussion).

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend_profile.go
> +		{
There are no (?) {} in the multi-line case statements elsewhere, as quick search shows.

2024-11-26 04:11 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend_profile.go
> +			case "desktop-wayland":
why not:

```
			switch devtype {
			case "ssh-agent":
				pr.Agent = &workshop.SshAgent{Name: name, Connect: dev["connect"], Listen: dev["listen"]}
			case "desktop-wayland":
				pr.Desktop.Wayland = &workshop.ProxyEntry{Name: name, Connect: dev["connect"], Listen: dev["listen"]}
			case "desktop-x11":
				pr.Desktop.X11 = &workshop.ProxyEntry{Name: name, Connect: dev["connect"], Listen: dev["listen"]}
			default:
				logger.Noticef("On reading %q SDK profile: unknown device type: %s", profile, devtype)
			}
```

It would also use the same semantics (nil pointer indicates that value can be not set), so you don't have to compare the name of the ProxyEntry for "", if it is nil, it does not exist.

2024-11-26 04:30 UTC, lachypjones commented on internal/interfaces/builtin/desktop.go
> +		x := &desktop.X11
No specific reason. I understand it's probably easier to read it without having to understand what d actually refers to. No problem

2024-11-26 04:36 UTC, lachypjones commented on internal/interfaces/lxd_device/spec.go
> +func (s *Specification) SetDesktop(desktop *workshop.Desktop) error {
Again, happy to change for consistency's sake. 
Why make a copy when it's cheaper to copy a pointer, legitimately interested. I understand it's a *tiny* data structure

2024-11-26 04:37 UTC, lachypjones commented on internal/interfaces/lxd_device/spec.go
> +	addProxyEntry(s, (*workshop.ProxyEntry)(&agent), "ssh-agent")
Fair call.
I wanted to avoid modifying all the unit tests in-case you were not happy with breaking things out into a struct. This was the smallest modification way of doing that.

2024-11-26 05:58 UTC, dmitry-lyfar commented on internal/interfaces/lxd_device/spec.go
> +func (s *Specification) SetDesktop(desktop *workshop.Desktop) error {
Having a copy tells you that you control its life-time vs. having a pointer that is allocated and managed by someone else. Also, the client sees there will be no modification. Pointers in these cases are an unnecessary level of indirection and performance considerations are not something I would optimise for. Also, https://go.dev/wiki/CodeReviewComments#pass-values

The usage of pointers internally is intentional; that allows to check whether a device installed without inspecting its fields.

2024-11-26 14:32 UTC, akcano commented on docs/explanation/interfaces/desktop-interface.rst
> +This means the host's Wayland/X11 socket is available inside the workshop:
```suggestion
This means the host's socket (Wayland, X11 or both) is available inside the workshop:
```
@lachypjones I have *strong* feelings about the use of slashes as punctuation. Make English great again!

2024-11-26 22:17 UTC, lachypjones commented on docs/explanation/interfaces/desktop-interface.rst
> +This means the host's Wayland/X11 socket is available inside the workshop:
@akcano I like this last suggestion.
I'll make a minor edit 
```suggestion
This means the host's display socket (Wayland, X11 or both) is available inside the workshop:
```

2024-11-27 23:03 UTC, lachypjones commented on internal/workshop/lxd/lxd_backend.go
> +		"raw.lxc":                  "lxc.mount.entry = tmpfs tmp tmpfs defaults",
I think I'll get rid of this.
If we're going to symlink the Xauth cookie, we mightaswell symlink the X and Wayland sockets also?

2024-11-28 09:14 UTC, akcano approved these changes

2024-12-02 00:24 UTC, dmitry-lyfar approved these changes
This looks great. I'm happy to merge it, just a few remarks requested.

2024-12-02 00:24 UTC, dmitry-lyfar commented on internal/interfaces/builtin/desktop_test.go
> +}
```suggestion
}

```

2024-12-02 00:24 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/ifacemgr.go
> +		usr, err := workshop.LookupUsername(user)
I would extract it as a separate function, similarly to `recreateInternalMounts`, e.g. `updateXAuthority`.

2024-12-02 00:24 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +// The following 'write-files' and 'runcmd' sections are for the desktop
Please extend why we do a copy instead of a symlink.

2024-12-02 00:24 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +// work around file mount ordering complications with lxc. Although these will
```suggestion
// work around file mount ordering complications with lxc (files, mounted at /tmp, are not visible; mounts at /tmp are generally advised against in LXD). Although these will
```

2024-12-02 00:24 UTC, dmitry-lyfar commented on internal/workshop/lxd/lxd_backend.go
> +		// directory) to allow us to mount X11 sockets reliably
```suggestion
		// directory) to allow us to mount X11 sockets reliably
		// See: https://github.com/lxc/lxc/issues/434
```

2024-12-02 00:24 UTC, dmitry-lyfar commented on tests/lib/sdk/test-sdk-desktop/sdk/hooks/setup-base
> +#!/usr/bin/bash
FYI, this is not required.

2024-12-02 00:24 UTC, dmitry-lyfar commented on tests/main/interface-desktop/task.yaml
> +summary: Check desktop interface scenarios
This is a very nice test suite. I would add one more scenario (as a separate empty workshop definition here): refresh to a new workshop definition that does not have the desktop plug. Would be handy to guard scenarios we are going to have when we expand Workshop to support per-SDK refreshes or partial refresh.

2024-12-02 02:25 UTC, jonathan-conder commented on docs/explanation/interfaces/index.rst
> +:ref:`desktop <exp_desktop_interface>` and ref:`SSH <exp_ssh_interface>`
```suggestion
:ref:`desktop <exp_desktop_interface>` and :ref:`SSH <exp_ssh_interface>`
```

2024-12-02 04:26 UTC, merged