Remove prefix from workshop definitions
canonical/workshop pull request #221
Opened 2024-11-29 04:25 UTC by jonathan-conder

# Description

Allowing `workshop.yaml` at the project level makes `missing-file` warnings more complicated. There are a few situations:
1) `workshop.yaml` and `.workshop/<NAME>.yaml` are absent
2) `workshop.yaml` is a different workshop, and `.workshop/<NAME>.yaml` is absent
3) `workshop.yaml` is a different workshop, and `.workshop/<NAME>.yaml` is present
4) `workshop.yaml` is invalid, and `.workshop/<NAME>.yaml` is absent
5) `workshop.yaml` is invalid, and `.workshop/<NAME>.yaml` is present

Originally I took a basic approach which reports `missing-file` for 1, 2 and 4. But 3 and 5 are also "cannot refresh" states, so maybe they should also trigger `missing-file`, or a different warning. Arguably 4 should also be a different warning.

After discussing with @dmitry-lyfar we've decided to remove `missing-file` entirely, since the file only really needs to be there for launch and refresh, which will raise errors anyway.

However, if `workshop.yaml` is invalid, we show a new warning in `workshop list` because the output may be incomplete.

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.
 * [x] Follow the [style guide](https://github.com/canonical/workshop/tree/main/docs/contributing.rst#error-messages) for new error messages.

## Docs

* [x] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [x] I have included the technical author in the review.

Or:

* [ ] I confirm the PR has no implications for documentation.

2024-11-29 10:03 UTC, akcano requested changes

2024-11-29 10:03 UTC, akcano commented on docs/explanation/workshops-sdks/workshops.rst
> +for example :file:`.workshop/golang.yaml`.
```suggestion
If a project defines more than one workshop,
the definitions should be stored in the :file:`.workshop/` directory
(for example, :file:`.workshop/golang.yaml`).
```

2024-11-29 10:03 UTC, akcano commented on docs/reference/workshop-definition.rst
> +with the filename :file:`<NAME>.yaml`.
```suggestion
When multiple workshops are defined,
their YAML definition files must be stored in the :file:`.workshop/` subdirectory.
```

2024-11-29 10:03 UTC, akcano commented on docs/reference/workshop-definition.rst
> +in the project folder.
```suggestion
in the project directory.
```

2024-11-29 10:03 UTC, akcano commented on docs/reference/workshop-definition.rst
> +       For workshops defined in the :file:`.workshop` folder,
```suggestion
       For workshops defined in the :file:`.workshop/` subdirectory,
```

2024-11-29 10:03 UTC, akcano commented on docs/reference/workshop-definition.rst
> +with the filename :file:`<NAME>.yaml`.
'Folder' is my oversight, should avoid that kind of language.

2024-12-01 20:40 UTC, jonathan-conder commented on docs/reference/workshop-definition.rst
> +with the filename :file:`<NAME>.yaml`.
@akcano Removing `<NAME>.yaml` means the following paragraph doesn't make sense, so I've changed that as well. Let me know what you think

2024-12-02 03:41 UTC, jonathan-conder commented
A couple more commits on top of the doc changes:
- 1b1da97 removes the `missing-file` warning and note
- 805fa1a removes underscores from the workshop name regex. While testing `workshop launch` with no arguments, I noticed that LXD doesn't like underscores. So we might as well catch the error earlier on. I think it makes sense to include the change in this naming-related PR rather than the upcoming CLI PR.

Should be ready for review again (once the tests pass)

2024-12-02 04:28 UTC, dmitry-lyfar commented
@jonathan-conder sorry for creating additional work, I have just merged the desktop interface first since this PR was a long-time outstanding. It uses the old convention in the end-to-end tests that would fail on rebase here.

2024-12-02 04:30 UTC, jonathan-conder commented
yeah I thought that might happen, all good I'll merge those changes in and adjust

2024-12-02 11:12 UTC, akcano commented on docs/reference/workshop-definition.rst
> +with the filename :file:`<NAME>.yaml`.
@jonathan-conder it's OK.

2024-12-03 03:23 UTC, dmitry-lyfar commented on internal/workshop/project.go
> +func (w *Project) SingleWorkshop() (*File, error) {
I think `SingleWorkshop` deserves to become unexported; the tests should only test `Workshop()`. Also, as discussed, please consider `maybeSingleWorkshop()` for this.

2024-12-03 03:23 UTC, dmitry-lyfar commented on internal/workshop/project.go
>  func (w *Project) ReadWorkshops() ([]string, error) {
Consider:

```
touch workshop.yaml
workshop list
error: cannot list workshops: a workshop's name must: (1) start with a letter, (2) include only lowercase alphanumeric and hyphen characters
```

This error happens when a single workshop is broken AND when there are other workshops under .workshop/ conflicting with workshop.yaml. This is FYI as we have to parse something called workshop.yaml for the name, so this error will override other possible errors, e.g. other workshops also existing.

2024-12-03 03:24 UTC, dmitry-lyfar commented
Left some comments. Please also update the PR description (e.g. missing-file is gone now and it is hardly reversible).

2024-12-03 03:28 UTC, jonathan-conder commented on internal/workshop/project.go
> +func (w *Project) SingleWorkshop() (*File, error) {
thanks, that was an oversight because it was previously used for `missing-file`

2024-12-05 07:11 UTC, jonathan-conder commented on internal/workshop/project.go
>  func (w *Project) ReadWorkshops() ([]string, error) {
This should be better now:
1) If something is wrong with the files, `workshop list` will show a warning but continue to list running workshops.
2) These warnings, and error messages for `launch` and `refresh`, include more context.

@akcano can you please review the new error messages? They should all be in 3f34ca6 but the integrity test was updated in 607b25e

2024-12-05 21:02 UTC, akcano commented on docs/reference/schema.json
> +      "errorMessage": "A workshop's name must start with a letter and can only include lowercase alphanumeric and hyphen characters."
```suggestion
      "errorMessage": "A workshop's name must start with a letter and can only include digits, lowercase letters, and hyphens."
```

2024-12-05 21:04 UTC, akcano commented on tests/main/integrity-checks/task.yaml
> +    MATCH "invalid file \".*/new-project/.workshop.yaml\": a workshop's name must: \\(1\\) start with a letter, \\(2\\) include only lowercase alphanumeric and hyphen characters"
```suggestion
    MATCH "invalid file \".*/new-project/.workshop.yaml\": a workshop's name must: \\(1\\) start with a letter, \\(2\\) only include digits, lowercase letters, and hyphens"
```

2024-12-05 21:04 UTC, akcano commented on internal/workshop/workshop_file_test.go
> +	c.Assert(err, check.ErrorMatches, `a workshop's name must: \(1\) start with a letter, \(2\) include only lowercase alphanumeric and hyphen characters`)
```suggestion
	c.Assert(err, check.ErrorMatches, `a workshop's name must: \(1\) start with a letter, \(2\) only include digits, lowercase letters, and hyphens`)
```

2024-12-05 21:04 UTC, akcano commented on internal/workshop/workshop_file.go
> +		return nil, fmt.Errorf("a workshop's name must: (1) start with a letter, (2) include only lowercase alphanumeric and hyphen characters")
```suggestion
		return nil, fmt.Errorf("a workshop's name must: (1) start with a letter, (2) only include digits, lowercase letters, and hyphens")
```

2024-12-05 21:06 UTC, akcano commented on internal/workshop/project.go
> +		return nil, fmt.Errorf("more than one workshop, but %q not in %q subdirectory", path, Directory)
```suggestion
		return nil, fmt.Errorf("multiple workshops found, but %q not in %q subdirectory", path, Directory)
```

2024-12-05 21:06 UTC, akcano commented on internal/overlord/workshopstate/manager.go
> +		return nil, fmt.Errorf("project %q is not found", pId)
```suggestion
		return nil, fmt.Errorf("project %q not found", pId)
```

2024-12-05 21:06 UTC, akcano commented on internal/workshop/lxd/lxd_backend.go
> +		return nil, fmt.Errorf("project %q is not found", projectId)
```suggestion
		return nil, fmt.Errorf("project %q not found", projectId)
```

2024-12-05 21:07 UTC, akcano commented on internal/workshop/project.go
>  func (w *Project) ReadWorkshops() ([]string, error) {
@jonathan-conder done; even if I missed something, the general idea must be clear anyway.

2024-12-08 22:43 UTC, dmitry-lyfar approved these changes

2024-12-09 01:05 UTC, merged