Implement wait on error for launch
canonical/workshop pull request #225
Opened 2024-12-05 23:54 UTC by lachypjones

# Description

This PR allows use of the `--wait-on-error`, `--continue` and `--abort` flags with the `workshop launch` command.
The behavior mirrors that of the corresponding flags for `workshop refresh`. 

## Breaking Changes

- A launch/refresh aborted after using wait-on-error will now show `Undone` as the status of the change, rather than `Error`. This is done to work within the expectations of the state package. 
- 'RefreshMode' and all variations of the same concept (JSON representations, etc) have been renamed to 'Mode'.

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.
 * [x] Follow the [style guide](https://github.com/canonical/workshop/tree/main/docs/contributing.rst#error-messages) for new error messages.

## Docs

* [x] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [x] I have included the technical author in the review.

Or:

* [ ] I confirm the PR has no implications for documentation.

2024-12-06 02:00 UTC, lachypjones commented on docs/how-to/debug-workshop-issues.rst
> +     YYYY-MM-DDT00:00:00 ERROR command exit code 1
Note this change is not specific to this PR, I believe the documentation was incorrect.
 
@dmitry-lyfar this does then raise an interesting point though, the way that --wait-on-error reports what failed is worse than a transactional change. I was thinking of raising a separate PR to attempt to address this?

2024-12-06 13:22 UTC, akcano commented on docs/how-to/debug-workshop-issues.rst
> +:command:`workshop_tasks` commands discussed above
```suggestion
To determine what went wrong, use the :command:`workshop changes` and
:command:`workshop tasks` commands discussed above.
```

2024-12-06 13:23 UTC, akcano commented on docs/how-to/debug-workshop-issues.rst
> +     YYYY-MM-DDT00:00:00 ERROR command exit code 1
Command output in docs gets stale the moment you commit it; I'm looking at the ways to automate this as part of the general doc automation initiative.

2024-12-06 13:25 UTC, akcano commented on tests/main/launch-abort/task.yaml
> +  echo "Check the workshop launch --abort reverts to the previous state"
```suggestion
  echo "Check the 'workshop launch --abort' command reverts to the previous state"
```

2024-12-06 13:25 UTC, akcano commented on tests/main/launch-continue/task.yaml
> +  echo "Check the workshop launch --continue reverts to the previous state"
same as above

2024-12-06 13:25 UTC, akcano requested changes
LGTM with minor fixes

2024-12-09 01:00 UTC, dmitry-lyfar requested changes
Try to `workshop launch --continue` multiple times on a failed launch and then abort. There will be a lot of repeating errors reported and, also, an error logged by Errorf(task.Summary()). The error message on abort does already include errors, so there is no need to log something else. Also, as per the client code, it seems only the last error will be reported, not sure why duplicating errors are reported in the output.

Results of my smoke testing: another side effect of this change is that UnlinkSdk must check if the current link exists. As before it wasn't a possible scenario (there was always a 'current' link in a workshop for the SDK). Please address this (easy to reproduce with `test-sdk-content-broken`).

2024-12-09 01:00 UTC, dmitry-lyfar commented on client/projects.go
> +	ChangeMode string `json:"change-mode,omitempty"`
```suggestion
	ActionMode string `json:"action-mode,omitempty"`
```

2024-12-09 01:00 UTC, dmitry-lyfar commented on client/projects.go
> +	ChangeMode string `json:"change-mode,omitempty"`
The mode is used in the context of an action (refresh, launch, etc.) for a workshop. Change is a broader underlying concept.

2024-12-09 01:00 UTC, dmitry-lyfar commented on client/projects.go
> +	ChangeMode string `json:"change-mode,omitempty"`
Alternatively, it can be just `Mode`, as it is part of an action request already.

2024-12-09 01:00 UTC, dmitry-lyfar commented on client/projects.go
> +	ChangeMode string `json:"change-mode,omitempty"`
Also, please mention this in the comment for the PR (see the checkbox about breaking / irreversible changes).

2024-12-09 01:00 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +		taskset, err = mgr.LaunchMany(ctx, reqData.Names, pid, change.ID())
This, compared to `RefreshMany`, does not check for the workshop status as previously it did not make sense (the operation failed if workshop existed).

Now:

```

$ workshop launch --wait-on-error io
$ workshop launch io
error: cannot launch "io": workshop already exists
$ workshop changes
1168  Wait    today at 12:18 NZDT  -                    Launch "io" workshop

# this second change exist because it was created due to the lack of status check
1169  Hold    today at 12:19 NZDT  -                    Launch "io" workshop
```

2024-12-09 01:00 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +		taskset, err = mgr.LaunchMany(ctx, reqData.Names, pid, change.ID())
```
workshop launch --wait-on-error io
# errors out
workshop launch io 
# reports workshop exists AND creates a new change that's on Hold because there is no 
# status check in LaunchMany (see how refresh prevents it).
```

2024-12-09 03:13 UTC, lachypjones commented on internal/daemon/api_workshops.go
> +		taskset, err = mgr.LaunchMany(ctx, reqData.Names, pid, change.ID())
Refresh doesn't prevent creating holds.
```
35  Done    today at 13:38 ACDT  today at 13:38 ACDT  Launch "blank" workshop
36  Wait    today at 13:39 ACDT  -                    Refresh "blank" workshop
37  Hold    today at 13:39 ACDT  -                    Refresh "blank" workshop
38  Hold    today at 13:39 ACDT  -                    Refresh "blank" workshop
```

Tested on the current main branch.

2024-12-09 03:15 UTC, lachypjones commented on internal/daemon/api_workshops.go
> +		taskset, err = mgr.LaunchMany(ctx, reqData.Names, pid, change.ID())
This happens because we always create the change before performing the operation. I originally modified this behavior (as I thought it was a bug) however then noticed refresh did the same thing so kept it consistent. 

The status check itself is still an omission, I'll fix that now. 

Maybe we fix the hold behavior in a new PR?

2024-12-11 01:52 UTC, dmitry-lyfar requested changes

2024-12-11 01:52 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	var change = &state.Change{}
This initialisation is dangerous. It creates a non-nil change that does not exist in the state. See `st.NewChange` on how changes should be created. This must be a nil pointer here.

2024-12-11 01:52 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	switch {
It is if-else on a boolean flag, I would not do the switch assuming there are other scenarios yet .

2024-12-11 01:52 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	var change = &state.Change{}
Same here.

2024-12-11 01:52 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	switch {
Same here.

2024-12-11 01:52 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
>  	case "launch":
The `maybeResume` and `Mode` can be simplified this way (actually, I think it should just validate and return the mode):

```
// conflict.go
func (s Mode) Resume() bool {
	return s == ChangeContinue || s == ChangeAbort
}

// maybeResume -> actionMode
func actionMode(reqData *workshopReq) (conflict.Mode, error) {
	var mode conflict.Mode
	var err error

	mode, err = conflict.ParseMode(reqData.Options.Mode)
	if err != nil {
		return mode, resume, fmt.Errorf("cannot %s: %v", reqData.Action, err)
	}

	if len(reqData.Names) > 1 && mode != conflict.ChangeTransactional {
		return mode, resume, fmt.Errorf("wait-on-error is not supported for multiple workshops")
	}
	return mode, nil
}
```

I like that some additional refresh logic went to a separate func, that would make dispatching (if we decide to have it) easier. But I would suggest moving the resume parameters validation (i.e. `maybeResume`) before the dispatch and have it together with other request validation logic. This would resolve duplication in launch() and refresh(), free them from deciding on whether to resume or start a new one, and result in something like:

```
/// ...validation
	mode, err := actionMode(&reqData)
	if err != nil {
		return statusBadRequest(...)
	}

	var change *state.Change
	var taskset = []*state.TaskSet{}

// dispatching
	if mode.Resume() {
		change, err = conflict.ResumeAfterWait(st, reqData.Names[0], projectId, mode, reqData.Action)
	} else {
		switch reqData.Action {
		case "launch":
			change = newWorkshopChange(st, "launch", user, projectId, reqData.Action, reqData.Names)
			taskset, err = wsmgr.LaunchMany(r.Context(), reqData.Names, projectId, change.ID())
			change.Set("wait-setup", conflict.ChangeSetup{Mode: mode.String()})
		case "refresh":
			// similar thing, but keep the function refresh() as it has more logic
		case "start":
			change = newWorkshopChange(st, "start", user, projectId, reqData.Action, reqData.Names)
			taskset, err = wsmgr.StartMany(r.Context(), reqData.Names, projectId, change.ID())
		case "stop":
			change = newWorkshopChange(st, "stop", user, projectId, reqData.Action, reqData.Names)
			taskset, err = wsmgr.StopMany(r.Context(), reqData.Names, projectId, change.ID())
		case "remove":
			change = newWorkshopChange(st, "remove", user, projectId, reqData.Action, reqData.Names)
			taskset, err = wsmgr.RemoveMany(r.Context(), reqData.Names, projectId, change.ID())
		default:
			return statusBadRequest("unknown action")
		}
	}
```

2024-12-11 02:31 UTC, dmitry-lyfar commented
@akcano can you please have a look into the new error and log messages, specifically, Aborting... and Continuing... for --continue and --abort?

2024-12-11 04:16 UTC, lachypjones commented on internal/daemon/api_workshops.go
>  	case "launch":
I really liked this approach, however there is a problem.
The mode is only set for 'launch' and 'refresh' commands, there is not a clean way to incorporate the above because it needs to check the mode first.

We can 'assume' the mode is transactional if it's otherwise unset, however I don't think that's a good solution.

2024-12-11 04:31 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
>  	case "launch":
@lachypjones the default mode for all actions is, indeed, transactional because it is an action's mode not refresh or launch mode anymore. For some actions, only the transactional mode is supported. What is the exact problem with this?

2024-12-11 04:40 UTC, lachypjones commented on internal/daemon/api_workshops.go
>  	case "launch":
We only set the mode explicitly for 'launch' and 'refresh'. For all other modes it's inferred (and an optional parameter in the marshalled JSON). If we then infer here, we miss any cases where a caller did not explicitly set for 'launch' and 'refresh'. 

If you're happy with this as a solution, then there is no problem. I assumed from the error messages and current tests (ie. IncorrectInput) that we wanted this to be an explicit choice.

2024-12-11 04:58 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
>  	case "launch":
This should be encapsulated by `actionMode()` which:

1. Will validate compatibility of the mode and the action requested. So that action: start and mode: wait-on-error gets declined by the API call at the validation stage.
2. Infer the mode value.
3. Will ensure that the mode is provided for the actions that require it (so for the `launch` and `refresh` actions the piece of code that sets it to the default mode anyway, I don't think it is happening in your `maybeResume` now. So, if I call a launch with an empty mode attribute, it won't work).

2024-12-11 11:15 UTC, akcano commented on cmd/workshop/launch.go
> +		"Abort the previously paused operation, removing any changes.")
```suggestion
		"Abort the previously paused operation, reverting any changes.")
```

2024-12-11 11:16 UTC, akcano commented on cmd/workshop/launch.go
> +		return fmt.Errorf("cannot launch: '--wait-on-error' incompatible with multiple workshops")
Not sure what's going on with the conditional logic here.

2024-12-11 11:18 UTC, akcano commented on cmd/workshop/launch.go
> +		"Abort the previously paused operation, removing any changes.")
The auto-generated docs do not match this for some reason, so make sure to regenerate the CLI docs with the updated commit.

2024-12-15 20:38 UTC, lachypjones commented on cmd/workshop/launch.go
> +		return fmt.Errorf("cannot launch: '--wait-on-error' incompatible with multiple workshops")
This matches exec. 
I'll add a comment for clarity

2024-12-15 20:41 UTC, lachypjones commented on cmd/workshop/launch.go
> +		"Abort the previously paused operation, removing any changes.")
This is for the launch command.
I believe 'remove' makes more sense here.
(essentially we disconnect interfaces and remove the container, we don't revert to a previous state like with refresh)

2024-12-16 04:55 UTC, dmitry-lyfar requested changes

2024-12-16 04:55 UTC, dmitry-lyfar commented on internal/overlord/workshopstate/manager.go
> +	switch {
You don't use CheckStatus for the launch anymore, is there a reason to keep these changes?

2024-12-16 04:55 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	switch reqData.Action {
This is from our conversation:

> It's an action's mode, agnostic of action as per the name.
> That's why it has to be an optional parameter with a default value.

> Sounds good

That means that you don't have to 1. specify transactional mode for all other actions in the tests, 2. you only need to check if it is empty to set to the default value. Then you can validate compatibility between an action and the mode:

> this is the validation function's actionMode job: validate and infer; fail if options are invalid, incompatible, etc.

Also, the logic below, does it allow for the "launch" action with no mode provided?

2024-12-16 05:06 UTC, lachypjones commented on internal/overlord/workshopstate/manager.go
> +	switch {
I kept this because the previous healthcheck implementation has OffStatus as a valid case in the switch statement, however it's impossible to reach this state without these changes.

2024-12-18 22:55 UTC, dmitry-lyfar commented on internal/daemon/api_workshops_test.go
> +				"wait-on-error": `cannot stop: mode "wait-on-error" is not valid with this command`,
We should specify the command name, something like `is not valid with "stop" command`.

2024-12-18 22:55 UTC, dmitry-lyfar commented on internal/daemon/api_workshops_test.go
> +			cmd:   "invalid-cmd",
This test looks much cleaner. What we can also do is to validate the action before it gets to dispatching, so you actually don't have to parse mode if the action is not supported. This will rid you of the last two rows in your table ("invalid-cmd" and "").

The `valid` flag can go away too if you move the unknown action into a separate test. So, this will check modes and there will be a separate small test that checks actions validity.

2025-01-05 23:06 UTC, dmitry-lyfar commented on cmd/workshop/wait.go
> +			// if the change finished as Undone and reported an error, check if
@lachypjones I think the entire comment should be updated as it is no longer true.

2025-01-05 23:16 UTC, lachypjones commented on cmd/workshop/wait.go
> +			// if the change finished as Undone and reported an error, check if
See what I've worded it to now.
I think the bulk of the comment still accurately reflects what we're doing (iterating through the task history and checking for errors which reflect abort itself failing). The language around task log needed correcting.

2025-01-05 23:22 UTC, dmitry-lyfar commented on cmd/workshop/wait.go
> +			// if the change finished as Undone and reported an error, check if
Yes, also: it was an expected abortion of a failed refresh -> it was an expected abortion OR a failed change

2025-01-06 23:36 UTC, dmitry-lyfar commented on internal/overlord/workshopstate/request.go
> +		} else if err != workshop.ErrWorkshopNotLaunched {
```suggestion
		} else if !errors.Is(err, workshop.ErrWorkshopNotLaunched) {
```

2025-01-07 01:01 UTC, dmitry-lyfar approved these changes

2025-01-07 01:01 UTC, merged