Make workshop name optional for some commands
canonical/workshop pull request #226
Opened 2024-12-09 02:55 UTC by jonathan-conder

# Description

If a project only has one workshop, the `launch`, `refresh`, `info`, `start`, `stop`, `remove`, `exec`, `shell` and `hack` commands no longer require a workshop name. Internally, these commands call `v1GetProjectWorkshops` and, if the result has a single entry, proceed as before.

The `v1GetProjectWorkshops` API has been extended slightly: the `state` query parameter can be `available`, `all`, or an actual state. The new state `available` is similar to `all`. It shows existing workshops and workshop files. If something is wrong with the workshop files, `available` downgrades the error to a warning and lists the existing workshops, whereas `all` returns the error. The actual states work the same as before (since they ignore workshop files).

Now `workshop list` uses `state=available`, but commands without workshop names use `state=all`, which remains the default if no `state` is provided.

The `exec` command is a special case, because in `workshop exec one two` it's unclear if `one` is the workshop name or the start of a command. The ambiguity is resolved by the presence or absence of a separator (`--`): `workshop exec -- one two` will treat `one two` as a command, whereas `workshop exec one two`, `workshop exec one -- two` and `workshop exec one two --` all run the `two` command in the workshop named `one`.

This PR also tells cobra to stop parsing `exec` arguments after the workshop name. We still remove the first `--` by hand if needed. So for example `workshop exec foo bar --project $P` will now run the command `bar --project $P` in the current project, rather than running `bar` in project `$P`. This is not required for the above `exec` changes, but I think it improves ergonomics, and without this I would be inclined to make `--` mandatory.

Where possible I've updated the tests to remove workshop names from commands. I think there's a nice mix of single- and multi-workshop projects so we should have pretty good coverage of both scenarios. Also updated some unit tests but I haven't added new ones just for this.

Following up on [Dmitry's observation](https://github.com/canonical/workshop/pull/226#issuecomment-2529863557), I've refactored the project tracking logic. I hope it's easier to follow now, but it should have the same behaviour as before, except fewer errors are suppressed (23367e8c583847b12c3a98359b556ccad6d424ba, 14edb67887a4e78c6f4b6b0278cdecc6bc07fbb1, 15ad5fd0100cc688640b1fdbb8de70a6ecfd11b1, 218365694d0e0b55be1907127d9e88408356acd5) and some steps have been reordered.

The latency seems to be caused by multiple projects/workshops and missing-project warnings. One step to address this in future might be to add a `Project()` method to the backend, to avoid the overhead of `Projects()` when the project ID is already known.

There also seems to be a bug where an empty `.workshop.lock` can be created, but I haven't been able to reproduce it reliably. Maybe these changes will fix it anyway.

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.
 * [x] Follow the [style guide](https://github.com/canonical/workshop/tree/main/docs/contributing.rst#error-messages) for new error messages.

## Docs

* [ ] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [x] I have included the technical author in the review.

Or:

* [ ] I confirm the PR has no implications for documentation.

2024-12-09 23:54 UTC, dmitry-lyfar commented
@jonathan-conder thank you! I will get to reviewing it shortly. Whilst the review is in progress, could you think of the following issue: now, commands like `info` have a noticeable delay compared to how it was before when it had only a single API call. These are my `info` calls on the server:

```
GET /v1/projects/984d2192/workshops 242.042578ms 200
GET /v1/projects/984d2192/workshops/optional 117.13134ms 200

GET /v1/projects/984d2192/workshops 247.191314ms 200
GET /v1/projects/984d2192/workshops/optional 128.266784ms 200
```

These are the results for `workshop list --global` (I have several projects, some with warnings):

```
GET /v1/projects 117.29467ms 200
GET /v1/projects/fbc4e283/workshops?state=available 236.121388ms 200
GET /v1/projects/0ce2e11f/workshops?state=available 234.223879ms 200
GET /v1/projects/502e3034/workshops?state=available 226.706331ms 200
GET /v1/projects/4d42157d/workshops?state=available 237.659068ms 200
GET /v1/projects/984d2192/workshops?state=available 256.764649ms 200
GET /v1/projects/24d984c1/workshops?state=available 242.050375ms 200
GET /v1/projects/ad51bb1d/workshops?state=available 259.657018ms 200
```

2024-12-19 02:31 UTC, dmitry-lyfar requested changes
Great work. Some minor issues.

2024-12-19 02:31 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +		case "all":
```suggestion
		case "all", "available":
```

2024-12-19 02:31 UTC, dmitry-lyfar commented on internal/daemon/api_workshops.go
> +	if wstate == "all" || wstate == "available" {
We only have two valid states here and state is an optional field. Could you add the query parameters validation before the actual logic, so this condition would become not relevant, as it will be executed for any request.

2024-12-19 03:18 UTC, jonathan-conder commented
@akcano This should be ready in terms of changes to the docs at least. The main things are:
1. Removing workshop names from example commands (my rule of thumb was to do this only if the workshop definition file is listed earlier on).
2. Adding a tip about how this works for `exec` in the tutorial.
3. Adding nameless examples to the affected commands.

2024-12-19 04:20 UTC, dmitry-lyfar approved these changes

2024-12-19 09:59 UTC, akcano approved these changes
LGTM, a couple of minor changes.

2024-12-19 09:59 UTC, akcano commented on docs/reference/cli/workshop-stop.rst
> +The name is optional if the project only has one workshop:
```suggestion
The name is optional if the project has only one workshop:
```

Please apply globally.

2024-12-19 09:59 UTC, akcano commented on docs/tutorial/index.rst
> +   it can be omitted from most :samp:`workshop` commands.
```suggestion
   it can be omitted from most :command:`workshop` commands.
```

2024-12-20 00:36 UTC, merged