Sketch SDK
canonical/workshop pull request #229
Opened 2024-12-12 04:04 UTC by dmitry-lyfar

# Description

This PR updates the `sketch-sdk` (formerly, `hack`) workflow logic as follows:

```bash
$ workshop sketch-sdk           # Edits current Sketch SDK (opens an $EDITOR with a sketch template).
$ workshop sketch-sdk --stash   # Stashes; overwrites stash (if exists).
$ workshop sketch-sdk --restore # Restores from stash; fails if there is a current Sketch SDK.
$ workshop sketch-sdk --remove  # Removes current Sketch SDK.
```

`workshop remove` will remove both current and stashed `sketch` SDKs to be consistent with the command's approach to resources created by a workshop (e.g. the default mount directories will be removed as well if weren't `remount`).

## Breaking Changes (API)

- [Change /v1/workshops to return workshops and files separately](https://github.com/canonical/workshop/pull/229/commits/befd10497a336c2ede5948777acc231ec2392bd6).
- [Change /v1/projects/{id}/workshops to include file info if present](https://github.com/canonical/workshop/pull/229/commits/2cead7e336070fb770aed9f6f7f44bbbccd8c3b1).

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.
 * [x] Follow the [style guide](https://github.com/canonical/workshop/tree/main/docs/contributing.rst#error-messages) for new error messages.

## Docs

* [x] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [ ] I have included the technical author in the review.

Or:

* [ ] I confirm the PR has no implications for documentation.

2024-12-12 21:45 UTC, akcano requested changes

2024-12-12 21:45 UTC, akcano commented on cmd/workshop/sketch.go
> +which installs the updated 'sketch' SDK in the workshop.
```suggestion
This opens the 'sketch' SDK definition in the default text editor,
enabling rapid experiments and tweaks at the SDK level.

Saving the definition and exiting the editor causes a refresh,
which installs the configured 'sketch' SDK in the workshop.
```

2024-12-12 21:45 UTC, akcano commented on cmd/workshop/sketch.go
> +The '--remove' option removes the 'sketch' SDK permanently.
```suggestion
The '--stash' and '--restore' options respectively stash the SDK,
reversing the changes, and quickly restore it to the workshop.
The '--remove' option removes the SDK permanently.
```

2024-12-12 21:45 UTC, akcano commented on cmd/workshop/sketch.go
> +# https://canonical-workshop.readthedocs-hosted.com/en/latest/explanation/sdks/
I'd suggest parameterizing the URLs and adding a `curl`-based test for them.

2024-12-12 23:27 UTC, jonathan-conder requested changes
Looks good, some minor issues though

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +		RunE: c.Run,
The `Examples` seem to have disappeared

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +    #   workshopctl set-health --code=installation-fails error "Installation fails"
```suggestion
    #   workshopctl set-health --code=installation-failed error "Installation failed"
```

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +		// workshop refresh --abort and workshop sketch --restore to restore the
```suggestion
		// workshop refresh --abort and workshop sketch-sdk --restore to restore the
```

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +	boilerplate := fmt.Sprintf(sketchTemplate, workshop.Filepath(p.Path, wp.Name), wp.Base)
With the new conventions, `workshop.Filepath` might not be correct here (it will always give `.workshop/<NAME>.yaml`)

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +		return fmt.Errorf("cannot sketch: SDK name must be %q", sdk.Sketch)
```suggestion
		return fmt.Errorf("cannot sketch: SDK must be named %q (now: %q)", sdk.Sketch, rec.Name)
```
For consistency with https://github.com/canonical/workshop/blob/c97e38cf668bb111f713c98fa61227a49db081d8/internal/workshop/project.go#L76

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +			if err := os.Remove(hookpath); err != nil && !osutil.IsDirNotExist(err) {
```suggestion
			if err := os.Remove(hookpath); err != nil && !errors.Is(err, os.ErrNotExist) {
```
This confused me a bit because `hookpath` isn't a directory

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +		return cmdrefresh.Run(cmd, av[0:1])
```suggestion
		return cmdrefresh.Run(cmd, av)
```
I think there's another line with this somewhere as well. I might change it in my PR anyway so feel free to leave as-is.

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch_test.go
> +	sketchContent := fmt.Sprintf(sketchTemplate, workshop.Filepath(m.prjDir, "ws"), "ubuntu@22.04")
If you change the other `Filepath`, this one should change too

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch_test.go
> +
In https://github.com/canonical/workshop/commit/6c97ccbbd96f6f8e0a7956ee2e68c441eafcfbd0 there was a test similar to this which wasn't calling all the mocked endpoints, so I think it's a good idea to check that `n==5` here

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch_test.go
> +	c.Assert(filepath.Join(hooks, "save-state"), testutil.FileEquals, `# saves state`)
I think we should append newlines to hooks even if the user does something like `|-`. At least that's what I'm doing for scripts, and it would be good to be consistent here. I can add it as part of the scripts work if you prefer.

2024-12-12 23:27 UTC, jonathan-conder commented on cmd/workshop/sketch_test.go
> +		err := os.WriteFile(inPath, []byte(sketchContent), 0644)
I don't understand why this mock is writing the file. The other mocks just return the content.

2024-12-12 23:27 UTC, jonathan-conder commented on docs/reference/cli/index.rst
> +.. include:: workshop-sketch-sdk.rst
This is no longer in alphabetical order - I suggest running `workshop generate-docs` and just copy the files over. This is the diff I see:
```diff
diff --color -Nru docs/reference/cli/index.rst docs-gendocs/index.rst
--- docs/reference/cli/index.rst	2024-12-13 11:59:59.809975659 +1300
+++ docs-gendocs/index.rst	2024-12-13 12:01:37.449277664 +1300
@@ -24,9 +24,6 @@
 .. include:: workshop-exec.rst
 
 
-.. include:: workshop-sketch-sdk.rst
-
-
 .. include:: workshop-info.rst
 
 
@@ -51,6 +48,9 @@
 .. include:: workshop-shell.rst
 
 
+.. include:: workshop-sketch-sdk.rst
+
+
 .. include:: workshop-start.rst
 
 
diff --color -Nru docs/reference/cli/workshop-refresh.rst docs-gendocs/workshop-refresh.rst
--- docs/reference/cli/workshop-refresh.rst	2024-12-13 11:59:59.809975659 +1300
+++ docs-gendocs/workshop-refresh.rst	2024-12-13 12:01:37.448277621 +1300
@@ -52,7 +52,7 @@
 
 - If the optional <SDK> is supplied,
   the operation is limited to this SDK;
-  currently, it can only be 'hack'
+  currently, it can only be 'sketch'
 
 
 .. rubric:: Options
@@ -106,8 +106,10 @@
    $ workshop refresh nimble --continue
 
 
-Refresh the :samp:`sketch` SDK in :samp:`nimble`:
+Refresh the hack SDK under 'nimble':
 
 .. code-block:: console
 
-   $ workshop refresh nimble/sketch
+   $ workshop refresh nimble/hack
+
+
diff --color -Nru docs/reference/cli/workshop-sketch-sdk.rst docs-gendocs/workshop-sketch-sdk.rst
--- docs/reference/cli/workshop-sketch-sdk.rst	2024-12-13 11:59:59.809975659 +1300
+++ docs-gendocs/workshop-sketch-sdk.rst	2024-12-13 12:01:37.448277621 +1300
@@ -54,3 +54,5 @@
 --stash
 
    Stash the sketch SDK and remove it from the workshop.
+
+
```
Looks like `cmd/workshop/refresh.go` still has some `hack` references

2024-12-13 03:47 UTC, dmitry-lyfar commented on cmd/workshop/sketch.go
> +	boilerplate := fmt.Sprintf(sketchTemplate, workshop.Filepath(p.Path, wp.Name), wp.Base)
It turns out that the client cannot infer it anymore. See my latest commit, I went down the path of including the workshop's file path into the response for both, active and file-only workshops. It is a breaking change for the existing workshops that, I believe, we should do as the convention changes made reliance on the Filepath incorrect.

I also cleaned up the Filename function from the workshop package as it is incorrect too (made it unexported for the case it is currently used for). I think we should retire the Filepath function too as a separate change as it is mainly used in tests.

2024-12-13 03:58 UTC, jonathan-conder commented on internal/workshop/workshop_file.go
>  	if err = yaml.Unmarshal(buf, &file); err != nil {
I think the path should be set after `Unmarshal`, or we should exclude `Path` from unmarshalling if that's possible

2024-12-13 04:04 UTC, jonathan-conder commented on cmd/workshop/sketch.go
> +	boilerplate := fmt.Sprintf(sketchTemplate, workshop.Filepath(p.Path, wp.Name), wp.Base)
I was a bit hesitant to go down this path myself, I think the path for running workshops can potentially be out-of-date. In `v1GetProjectWorkshop`, when listing the files, I think we should update the paths for the existing workshops. That way it will only be out of sync if the request specifies `state=ready` or something.

I agree `Filepath` makes less sense now.

2024-12-13 04:49 UTC, jonathan-conder approved these changes

2024-12-13 06:32 UTC, dmitry-lyfar commented on cmd/workshop/sketch.go
> +# https://canonical-workshop.readthedocs-hosted.com/en/latest/explanation/sdks/
We have those links under auth wall; any possible ways to do link checks similarly to how we do it in the docs?

2024-12-16 15:33 UTC, akcano commented on cmd/workshop/sketch.go
> +# https://canonical-workshop.readthedocs-hosted.com/en/latest/explanation/sdks/
The most simple way now is to check the two parts:

- the base URL (`https://canonical-workshop.readthedocs-hosted.com/en/latest/`), which we are certain of and can trim during the test
- the path (`explanation/sdks/`), which can be verified inside the repo by probing the respective directory under `docs/`.

2024-12-17 04:16 UTC, jonathan-conder commented on internal/workshop/project.go
>  // Read single workshop file if it exists and is unique.
This comment should be adjusted since it doesn't read the file anymore

2024-12-17 04:56 UTC, dmitry-lyfar commented on cmd/workshop/sketch.go
> +# https://canonical-workshop.readthedocs-hosted.com/en/latest/explanation/sdks/
Thanks. Will be moving it to the backlog to implement the actual link checks for when the documentation is open.

2024-12-17 05:02 UTC, merged