Prevent connection removal on backend setup failure
canonical/workshop pull request #231
Opened 2024-12-16 20:40 UTC by lachypjones

# Description
If an error occurs during the backend setup call within doDisconnect, the connection being disconnected will be left in a partially disconnected state. This error can be either transient (ie. a backend connection issue) or non-transient (ie. a broken workshop missing essential packages).

This PR restores the connection to the workshop state on failure, noting that this will not take any action to revert modifications to the workshop that were run during the disconnect (ie. remove<interface> functions).  

## One-way decisions
It was agreed that it's better to keep a potentially broken connection connected than to disconnect a potentially still-connected connection. Some of the factors going into this decision were the following:

- Transient errors 
  - It's better to let a user try again
- Ramifications for connect 
  - If we disconnect forcibly, it's highly possible we break any subsequent re-connections
- General guarantees
  - We should not allow an action (without making it explicitly clear) to break another action

# Self-review quick check

 * [x] Make decisions that cost a lot to reverse explicit in the PR description.
 * [x] Avoid nested conditions.
 * [x] Delete dead code and redundant comments.
 * [x] Normalise symmetries by sticking to doing identical things identically. 
 ```
 // one way to handle errors
 if err := f(); err != nil {
    ...
 }
 
 // one way to handle multiple returns
 val, err := f()
 if err != nil {
    ...
 }
 ...
 ```
 * [x] Check that coupled code elements, files, and directories are adjacent. For example, test data is stored as close as possible to a test.
 * [x] Put variable declaration and initialisation together.
 * [x] Divide large expressions into digestable and self-explanatory ones. Use multiple variables if required.
 * [x] Put a blank line between two logically different chunks of code.
 * [x] Follow the [style guide](https://github.com/canonical/workshop/tree/main/docs/contributing.rst#error-messages) for new error messages.

## Docs

* [ ] I have checked and added or updated relevant documentation.
* [ ] I have checked and added or updated relevant release notes.
* [ ] I have included the technical author in the review.

Or:

* [x] I confirm the PR has no implications for documentation.

2024-12-17 03:38 UTC, lachypjones commented
Only unit tests have been implemented. The coverage report for doDisconnect indicates that nearly all functionality (with the exception of some error conditions that are not impacted by this change) is covered.

2024-12-17 20:23 UTC, dmitry-lyfar requested changes

2024-12-17 20:23 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +	oldConns := maps.Clone(conns)
Try change your `TestDoDisconnectSetupFailure` this way:

1. Set the "connect" task `t1` to be an auto-connection by `t1.Set("auto", true)`
2. Have this plug definiotion for `consumerManyPlugs`:
```
  plug-ssh:
    interface: mock-ssh-agent
    attribute: four
```

2024-12-17 21:36 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers_test.go
> +	ref, err := repo.Connected(s.prj.ProjectId, "ws", "consumer", "plug-ssh")
Instead of checking if the reference exists, try to get the Connection object from the repo and ensure that the connection remained the same. There is a similar issue with a reverting Connect that should use a copy of the old connection in the 'auto' connection state.

2024-12-17 21:51 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +	oldConn := *conn
This solution solved the particular case for the auto, but it does not make full copy either. It happens to work because references to attrs are nullified, but if any of them was just changed, you'd get the same problem.

2024-12-17 22:04 UTC, lachypjones commented on internal/overlord/ifacestate/handlers.go
> +	oldConn := *conn
This consequence I did pick up on.
It didn't think it mattered in our case? I didn't see a situation where we would be modifying the map before the revert.

2024-12-18 02:16 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +	oldConn := *conn
It works here, but if it did change, the intention to create a copy that is indicated by dereferencing would not work. The copy that is created is a shallow copy either way. So it is implicit. 

There is this code that executes earlier exactly for this reason:

```
	// store old connection for undo
	task.Set("old-conn", conn)
```

You can use that in your revert logic and get the connection (full copy of it) from the task. That would be explicit and future-proof.

Potentially, you can even combine the repo and state reverters into a single one, they follow each other.

2024-12-18 18:51 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +		task.Get("old-conn", oldConn)
Error handling? Get returns an error.

2024-12-18 18:52 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +		oldConn := new(schema.ConnState)
We don't use new elsewhere, so just create on the stack and give its address to Get.

2024-12-18 23:16 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +		if err := task.Get("old-conn", oldConn); err != nil {
The lack of "old-conn" in the task's data should be an internal error. This is not a simple error, it's an integrity issue. So instead of proceeding and setting an empty connection to the state, we should return an internal error (see how these cases are handled a few lines above):

```
	if err := task.Get("forget", &forget); err != nil && !errors.Is(err, state.ErrNoState) {
		return fmt.Errorf("internal error: cannot read 'forget' flag: %w", err)
	}

```

2024-12-18 23:18 UTC, dmitry-lyfar commented on internal/overlord/ifacestate/handlers.go
> +		if err := task.Get("old-conn", oldConn); err != nil {
In our case you don't have to check for ErrNoState, any error here is an internal error.

2024-12-20 01:01 UTC, dmitry-lyfar approved these changes

2024-12-20 01:01 UTC, merged