Create snap for Workspace
canonical/workshop pull request #29
Opened 2023-08-18 03:22 UTC by dmitry-lyfar

2023-08-18 03:24 UTC, dmitry-lyfar commented on snap/snapcraft.yaml
> +summary: Workspace
@akcano The summary field has a limitation of 78 symbols that does not fit our headline. Hence, the headline went to the description field. WDYT should be here?

2023-08-18 07:43 UTC, jnsgruk commented on snap/snapcraft.yaml
> +base: core20
```suggestion
base: core22
```

2023-08-18 07:43 UTC, jnsgruk commented on snap/snapcraft.yaml
> +    source-type: local
```suggestion
    source-type: local
    build-snaps:
        - go/latest/stable
```

2023-08-18 07:43 UTC, jnsgruk commented on snap/snapcraft.yaml
> +    source-type: local
This will be needed if you switch to `core22`

2023-08-18 08:51 UTC, akcano commented on snap/snapcraft.yaml
> +summary: Workspace
@dmitry-lyfar 78 characters it is, then:
`Workspace automates intricate prerequisite setup for your development projects`

Also, take a look [here](https://docs.google.com/document/d/1NHFShs9zBsymdnLzsOEDpQ1O5H3b7gDYS7OVqkVgMpQ/edit) for an elaborated version.

2023-08-18 10:17 UTC, akcano requested changes
The snap worked like a charm on the host machine, thanks!
However, there were issues with actual workspace creation after installation, will report them privately.

On the VM, the snap failed; some `multipass`-related problems need investigation; will report them privately as well.

2023-08-18 10:17 UTC, akcano commented on docs/README.rst
> +Build and install the workspace snap package:
A bit of nitpicking; I suggest this:
`Build and install the ``workspace`` snap:`

Here, 'snap package' is a pleonasm; it deteriorates the messaging.
Compare to [this](https://snapcraft.io/docs/getting-started):

```
A snap is a bundle of one or more applications (“apps”) and their dependencies that works without modification across many different Linux distributions. Snaps are discoverable and installable from the [Snap Store](https://snapcraft.io/store), a public app store with an audience of millions.
```

No mention of packages.

2023-08-18 10:17 UTC, akcano commented on docs/README.rst
> +   git clone git@github.com:canonical/workspace.git
I suggest adding the HTTPS option. Not everyone have their SSH keys at the ready all the time:
```
git clone git@github.com:canonical/workspace.git
# -- or --
git clone https://github.com/canonical/workspace.git
```

2023-08-21 02:07 UTC, dmitry-lyfar commented on snap/snapcraft.yaml
> +    source-type: local
@jnsgruk thanks, added. With core22 I got [this](https://github.com/canonical/craft-providers/pull/182); although, looks like it was fixed. `snapcraft clean` solves the issue and, hopefully, it was a one-off problem due to snapcraft not disabling auto-refresh in my environment that was used to build core20 snaps.

2023-08-21 02:23 UTC, dmitry-lyfar commented on snap/snapcraft.yaml
> +    source-type: local
@jnsgruk sorry for a bunch of possible GitHub updates, I could not get it applied as a single batch on GitHub for some reason it fails to combine core22 suggestions. Also, snapcraft complains about plugs being in the global space for core22, changed that as well.

2023-08-21 02:39 UTC, dmitry-lyfar commented on docs/README.rst
> +Build and install the workspace snap package:
Updated, thanks!

2023-08-21 12:49 UTC, akcano approved these changes
Also, let's maybe monitor where we use these descriptions:
https://docs.google.com/spreadsheets/d/1KYo0NXiZHWB8YU51vKq4FGIBq9bne_tAW--azEw4c88

2023-08-21 14:32 UTC, jnsgruk approved these changes

2023-08-21 15:16 UTC, akcano requested changes

2023-08-21 15:16 UTC, akcano commented on docs/README.rst
> -save its pathname in the ``$WORKSPACE`` environment variable,
Seems we're losing this info with the update, but the snap installation doesn't work without the variable; can you please confirm the intended behaviour, @dmitry-lyfar ?

2023-08-21 21:27 UTC, dmitry-lyfar commented on docs/README.rst
> -save its pathname in the ``$WORKSPACE`` environment variable,
@akcano I suspect you still have ``workspace`` installed from sources which takes precedence over the one installed from snap. Try ``which workspace``; it is likely the binary from ``~/go/bin``, whilst it should be ``/snap/bin/workspace``. The ``WORKSPACE`` variable is set and used by snap, so no need to set it up in a normal scenario when you install it from snap.

2023-08-21 21:48 UTC, akcano commented on docs/README.rst
> -save its pathname in the ``$WORKSPACE`` environment variable,
@dmitry-lyfar confirmed, that's the case.

2023-08-21 21:48 UTC, akcano approved these changes

2023-08-21 22:23 UTC, merged